apiVersion: 1

groups:
  - name: Seguridad
    folder: Seguridad
    interval: 1m
    rules:
      - uid: errores_autenticacion_sospechosos
        alert: ErroresAutenticacionSospechosos
        title: Errores de Autenticación Sospechosos
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: loki
            model:
              expr: count(rate({job="varlogs"} |= "401" or |= "403"[$__rate_interval])) > 4
              format: table
              instant: true
              refId: A
        for: 1m
        labels:
          severity: warning
          tipo: seguridad
        annotations:
          summary: "Más de 4 errores 401/403 detectados"
          description: "Posible intento de acceso no autorizado o error recurrente de autenticación."
